name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django checks
        env:
          SECRET_KEY: test
          DEBUG: 'True'
        run: |
          python manage.py check --deploy --fail-level WARNING || true
      - name: Collect static
        env:
          SECRET_KEY: test
          DEBUG: 'True'
        run: |
          python manage.py collectstatic --noinput
